alt_glob:
  inputs: Coronavirus-Public-Arabic-Twitter-Data-Set-master/**/**.txt
alt_sep: ''
dataset_link: https://github.com/aseelad/Coronavirus-Public-Arabic-Twitter-Data-Set
dataset_name: CoronaVirus
datasets_path: datasets
encoding: utf-8
file_type: txt
header: true
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: true
local_dir: false
new_columns: tweet_id
pal: false
skiprows: 0
squad: false
xml_columns: ''
