alt_glob: []
alt_sep: ''
dataset_link: https://www.zenodo.org/record/6869079/files/Sudanese_dialect_speech_dataset.zip
dataset_name: sudanese_dialect_speech
datasets_path: datasets
file_type: wav
header: null
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: false
local_dir: false
new_columns: ''
pal: false
skiprows: 0
squad: false
xml_columns: ''
