pal: False
squad: False
local_dir: False
datasets_path: ""
hf_path : ""
dataset_name : ""
dataset_link: ""
alt_glob : {}
level : null 
file_type : ""
lines: True
json_key : null 
xml_columns : "" 
alt_sep : ""
skiprows: 0 
header: null 
new_columns: ""
label_column_name: ""
usecols: ""

