alt_glob:
  inputs: EDGAD-Female/Female/**.txt
alt_sep: tab
dataset_link: https://github.com/linuxscout/aghlat/blob/master/resources/abdnormal.txt.corpus.csv.wrong
dataset_name: aghlat
datasets_path: datasets
file_type: csv
header: true
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: true
local_dir: false
new_columns: ''
pal: false
skiprows: 0
squad: false
xml_columns: TIMEX3
