alt_glob: {}
alt_sep: tab
dataset_link: https://github.com/sjeblee/AOC/blob/master/stuff-from-omar/annotated-aoc-data/dialectid_data.tsv
dataset_name: annotated_aoc
datasets_path: datasets
file_type: csv
header: true
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: true
local_dir: false
new_columns: ''
pal: false
skiprows: 0
squad: false
usecols: HIT_info,HIT-ID,AID,AssignmentID,HITStatus,WorkerIP,WorkerCountry,WorkerCity,country_live,native_arabic,native_dialect,years_speaking,StartTime_str,EndTime_str,WorkTime,comment,Sentence1,DClass1,DLevel1,source1,document1,part1,segment1,Sentence2,DClass2,DLevel2,source2,document2,part2,segment2,Sentence3,DClass3,DLevel3,source3,document3,part3,segment3,Sentence4,DClass4,DLevel4,source4,document4,part4,segment4,Sentence5,DClass5,DLevel5,source5,document5,part5,segment5,Sentence6,DClass6,DLevel6,source6,document6,part6,segment6,Sentence7,DClass7,DLevel7,source7,document7,part7,segment7,Sentence8,DClass8,DLevel8,source8,document8,part8,segment8,Sentence9,DClass9,DLevel9,source9,document9,part9,segment9,Sentence10,DClass10,DLevel10,source10,document10,part10,segment10,Sentence11,DClass11,DLevel11,source11,document11,part11,segment11,Sentence12,DClass12,DLevel12,source12,document12,part12,segment12
xml_columns: ''
