alt_glob: []
alt_sep: ','
dataset_link: https://github.com/aub-mind/Arabic-Empathetic-Chatbot/blob/master/arabic-empathetic-conversations.csv
dataset_name: arabic_empathetic_conversations
datasets_path: datasets
file_type: csv
header: true
hf_path: ''
json_key: null
label_column_name: emotion
level: null
lines: false
local_dir: false
new_columns: ''
pal: false
skiprows: 0
squad: false
xml_columns: ''
