alt_glob:
- inputs: glob('*.txt')
- targets1: glob('*.wav')
alt_sep: ''
dataset_link: /home/zaid/dataset
dataset_name: mgb2
datasets_path: datasets
file_type: wav
header: null
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: false
local_dir: true
new_columns: ''
pal: false
skiprows: 0
squad: false
xml_columns: ''
