alt_glob: {}
alt_sep: ''
dataset_link: file.xml
dataset_name: CORMAP
datasets_path: datasets
file_type: xml
header: null
hf_path: ''
json_key: null
label_column_name: lang
level: null
lines: true
local_dir: true
new_columns: ''
pal: false
skiprows: 0
squad: false
usecols: text,lang
xml_columns: text,lang
