alt_glob: {}
alt_sep: ','
dataset_link: https://github.com/RashaMObeidat/ArQuAD
dataset_name: ArQuAD
datasets_path: datasets
encoding: latin-1
file_type: csv
header: true
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: true
local_dir: false
new_columns: ''
pal: false
skiprows: 0
squad: false
usecols: context,question,answer_start,text,title,id
xml_columns: ''
