alt_glob: []
alt_sep: tab
dataset_link: https://github.com/eligugliotta/tarc/blob/master/tarc.tsv
dataset_name: TArC
datasets_path: datasets
file_type: csv
header: true
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: false
local_dir: false
new_columns: ''
pal: false
skiprows: 0
squad: false
xml_columns: ''
