alt_glob: {}
alt_sep: ''
dataset_link: https://github.com/RashaMObeidat/ArEntail
dataset_name: ArEntail
datasets_path: datasets
file_type: xlsx
header: true
hf_path: ''
json_key: null
label_column_name: label
level: null
lines: true
local_dir: false
new_columns: ''
pal: false
skiprows: 0
squad: false
usecols: premise,hypothesis,label
xml_columns: ''
