alt_glob: {}
alt_sep: ','
dataset_link: TextualEn.txt
dataset_name: ArabicTE
datasets_path: datasets
encoding: utf-8
file_type: csv
header: true
hf_path: ''
json_key: null
label_column_name: Judgement
level: null
lines: true
local_dir: true
new_columns: ''
pal: false
skiprows: 0
squad: false
usecols: Premise,Hypothesis,Judgement
xml_columns: ''
