alt_glob: {}
alt_sep: tab
dataset_link: data.csv
dataset_name: AQweets
datasets_path: datasets
encoding: utf-8
file_type: csv
header: false
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: true
local_dir: true
new_columns: id,tweet,score
pal: false
skiprows: 0
squad: false
usecols: id,tweet,score
xml_columns: ''
