alt_glob: []
alt_sep: ;
dataset_link: https://github.com/chaymafourati/TUNIZI-Sentiment-Analysis-Tunisian-Arabizi-Dataset/blob/master/TUNIZI-Dataset.txt
dataset_name: TUNIZI
datasets_path: datasets
file_type: csv
header: false
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: true
local_dir: false
new_columns: sentiment,text
pal: false
skiprows: 0
squad: false
xml_columns: ''
