alt_glob: {}
alt_sep: ''
dataset_link: ./kaggle/lebanon-uprising-october-2019-tweets
dataset_name: Lebanon_Uprising_Arabic_Tweets
datasets_path: datasets
file_type: json
header: null
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: false
local_dir: true
new_columns: ''
pal: false
skiprows: 0
squad: false
usecols: screen_name,created_at,text,retweet_count,favorite_count,in_reply_to_screen_name,retweeted_status_screen_name,user_description,source,lang,id
xml_columns: ''
