alt_glob:
  inputs: InAra-Corpus/suspicious-documents/suspicious**.txt
alt_sep: ''
dataset_link: https://sourceforge.net/projects/inaracorpus/files/InAra-Corpus.zip
dataset_name: inaracorpus
datasets_path: datasets
encoding: utf-8
file_type: txt
header: true
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: false
local_dir: false
new_columns: Article
pal: false
skiprows: 0
squad: false
usecols: Article
xml_columns: ''
