alt_glob: {}
alt_sep: ''
dataset_link: https://archive.researchdata.leeds.ac.uk/464/1/AAQQAC.XML
dataset_name: AQQAC
datasets_path: datasets
file_type: xml
header: null
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: true
local_dir: false
new_columns: Question
pal: false
skiprows: 0
squad: false
usecols: Question,Answer,q_SRC_id,Source,Quetion_type
xml_columns: Question,Answer,q_SRC_id,Source,Quetion_type
