alt_glob: {}
alt_sep: ''
dataset_link: LabeledDataset.xlsx
dataset_name: Corpus_of_Offensive_Language_in_Arabic
datasets_path: datasets
file_type: xlsx
header: true
hf_path: ''
json_key: null
label_column_name: Label
level: null
lines: true
local_dir: true
new_columns: ''
pal: false
skiprows: 0
squad: false
xml_columns: ''
