alt_glob: {}
alt_sep: ''
dataset_link: https://github.com/telsahy/capstone-34/blob/master/34.210.104.115/eg_twitter_raw
dataset_name: Egyptial_Gulf_Twitter_Dataset
datasets_path: datasets
file_type: json
header: null
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: true
local_dir: false
new_columns: ''
pal: false
skiprows: 0
squad: false
usecols: created_at,id,id_str,text,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,in_reply_to_screen_name,user,geo,coordinates,place,contributors,retweeted_status,is_quote_status,quote_count,reply_count,retweet_count,favorite_count,entities,favorited,retweeted,possibly_sensitive,filter_level,lang,timestamp_ms,display_text_range,quoted_status_id,quoted_status_id_str,quoted_status
xml_columns: ''
