alt_glob: {}
alt_sep: ','
dataset_link: https://docs.google.com/spreadsheets/d/1S-vATi29FFviSQ5kmGvbVqP2N_G-IJqJntSoLgyg_ho/edit?gid=0#gid=0
dataset_name: cpt_culturax
datasets_path: datasets
encoding: utf-8
file_type: csv
header: true
hf_path: ''
json_key: null
label_column_name: ''
level: null
lines: true
local_dir: false
new_columns: ''
pal: false
skiprows: 0
squad: false
usecols: id,url,text,cleaned_text,filter
xml_columns: ''
